# General parameters:
# Keyswitch Cutout parameters:
keyswitch_width: 13.9
keyswitch_height: 13.8
keyswitch_space_below: 8.0 #used to determine the bottom of the case
plate_thickness: 2.0
side_nub_thickness: 4.0
retention_tab_thickness: 1.5
key_hole_rim_width: 1.5
create_side_nubs: False
# Global main grid layout parameters:
alpha: -15.0 # row angle delta (rotation around x), if not given explicitly
beta: -5.0 # column angle delta (rotation around y)
key_height: 12.7 # distance from the top of the plate to keycap surface, used to offset switches back
extra_height: 1.0 # additional row distance for the plate projection
extra_width: 2.5 # additional column distance for the plate projection
ncols: 5 # number of columns
column_angle_offset: 10.0 # angle for column 0, in case not all anlges are given explicitly
column_radius: 225.81701841662547
# Tenting and overall offset:
tenting_angle: 15.0  # number of columns
keyboard_z_offset: 10.
# Default Column:
default_column: # column parameters for columns that are not explicitly given. Angle is calculated as col * beta + offset
  nrows: 4
  row_angle_offset: 15.
  z_rotation_angle: 0.0
  column_offset: [0., 0., 0.]
  row_radius: 69.71780793741755
# Custom Columns, for custom settings, specify each column like this, it will overwrite the default
# Note: you need to specify ALL parameters if you give a specific column
column_0:
  angle: 10. #if angle is not given, it is calculate as col * beta + offset #TODO
  nrows: 3
  row_angle_offset: 15.
  z_rotation_angle: 0.0
  column_offset: [0., 0., 0.]
  row_radius: 69.71780793741755
column_1:
  angle: 5.
  nrows: 3
  row_angle_offset: 15.
  z_rotation_angle: 0.0
  column_offset: [0., 0., 0.]
  row_radius: 69.71780793741755
column_2:
  angle: 0.
  nrows: 4
  row_angle_offset: 15.
  z_rotation_angle: 0.0
  column_offset: [0., 2.82, -4.5]
  row_radius: 69.71780793741755
column_4:
  angle: -10.
  nrows: 3
  row_angle_offset: 15.
  z_rotation_angle: -0.0
  column_offset: [0., -12., 5.64]
  row_radius: 69.71780793741755
column_5:
  angle: -15.
  nrows: 3
  row_angle_offset: 15.
  z_rotation_angle: 0.0
  column_offset: [0., -12., 5.64]
  row_radius: 69.71780793741755
# Thumbs:
thumb_case: cone #cone, buble, bubbles
cone_segments: 500
n_thumbs: 5
thumb_box: intersection # oriented, square, intersection
rounded_thumb_case: True
thumb_radius: 3.0
thumb_space: [3., 3., 50.]
thumb_extra_x_space: 50.
# Case
main_grid_support_type: hulls # cylinders, hulls
case_thickness: 2.0  # wall thickness of the case
grid_xy_space: [10., 7.] # space to from the key perimeter to the edge of the box
rounded_grid_case: True
grid_radius: 3.0
space_below_lowest_switch: 2 # how far to end the box below the lowest switch
cut_relative_to_lowest_switch: 3  #how far below or above to put the case split
# screws:
screw_insert_od: 3.0
screw_insert_h: 5.0
screw_od: 2.6
screw_head_size: 4.0 # clearance fit
screw_inset: 3.5
thumb_screw_offset: [0., 5.]
thumb_extra_screw_offset: [56.5, -19.]
# trs holder:
trs_pcb_length: 13.1
trs_pcb_thickness: 1.8
trs_rest_width: 9.0
trs_y_offset: 24.

# microcontroller holder:
mc_pcb_length: 36.0
mc_pcb_thickness: 1.8
mc_rest_width: 9.0
mc_x_offset: 35.
